tokens:
    access-token-uri: https://auth.example.com/oauth2/access_token?realm=/yourrealm
    token-info-uri: https://auth.example.com/oauth2/tokeninfo
    token-configuration-list:
        - tokenId: producer
          scopes:
              - uid
              - producer.event_stream.read
        - tokenId: nakadi
          scopes: nakadi.event_stream.write
